### ISSUE TITLE
RFE: Expose which rules have a transform capabilitiy in docs and via CLI

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-lint#3624]
The per rule docs should show if a given rule has a transform ability.

We should also make the list of rules that have transform available from the CLI in aggregate.
```[tasklist]
### Tasks
- [x] Expose list of auto-fix rules in documentation
- [x] Make the auto-fix rule list dynamic in documentation using an include and generate_docs.py script
- [x] Fail generate_docs.py if a rule with autofix tag does not contain `autofix` inside its own markdownfile
- [x] Add documentation for all autofix rules. Required to be able to merge previous one.
```

**Comment by shatakshiiii** [comment]
Initial idea to expose auto-fix in upstream docs:

- Add a separate section for auto-fix over [here](https://ansible.readthedocs.io/projects/lint/), to explain what it does and to mention the list of rules covered by it 
(just like Profiles). Also link it to the per rule docs.
- The per rule doc should show the before and after behavior of using auto-fix (via examples)

More inputs are welcomed!
